spring:
  thymeleaf:
    cache: false
    #    prefix: classpath:/templates
    prefix: file:./src/main/resources/templates/
    servlet:
      content-type: text/html
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:paginasi;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console